#!/usr/bin/env bash
# generate-guidance.sh - 用零依赖方式生成精简的 agent guidance 入口文件

set -e

SOURCE_DOC="docs/agent-guidance/workflow.md"
GENERATED_HEADER="<!-- GENERATED BY scripts/multi-cli-sync/generate-guidance.sh. DO NOT EDIT DIRECTLY. -->"

# -----------------------------------------------------------------------------
# 配置区：在这里定义要生成的入口文件
# -----------------------------------------------------------------------------
TARGET_FILES=(
    "AGENTS.md"
    "CLAUDE.md"
    ".cursorrules"
    "COPILOT.md"
)

echo "🔄 开始生成 agent guidance 入口文件..."

if [ ! -f "$SOURCE_DOC" ]; then
    echo "❌ 错误：源文档 '$SOURCE_DOC' 不存在。"
    echo "请先创建它，作为所有代理共享的中心真值。"
    exit 1
fi

for file in "${TARGET_FILES[@]}"; do
    echo "➡️ 正在生成 $file..."
cat > "$file" <<EOF2
$GENERATED_HEADER

# Agent Workspace Instructions

This file is a thin entry point for coding agents working in this repository.

## Read First

1. \`$SOURCE_DOC\` — shared cross-agent workflow principles.
2. Task-relevant files in \`my-skills/*.md\` before taking action.

## Drift Rule

- Do not copy large instruction blocks into this file.
- Update the central source document (\`$SOURCE_DOC\`), then run \`bash scripts/multi-cli-sync/generate-guidance.sh\`.
EOF2
    echo "  ✔️ 已生成 $file"
done

echo "✅ agent guidance 入口文件生成完成！"
