# generate-guidance.ps1 - 用零依赖方式生成精简的 agent guidance 入口文件

$ErrorActionPreference = "Stop"

$SourceDoc = "docs/agent-guidance/workflow.md"
$GeneratedHeader = "<!-- GENERATED BY scripts/multi-cli-sync/generate-guidance.ps1. DO NOT EDIT DIRECTLY. -->"

# -----------------------------------------------------------------------------
# 配置区：在这里定义要生成的入口文件
# -----------------------------------------------------------------------------
$TargetFiles = @(
    "AGENTS.md",
    "CLAUDE.md",
    ".cursorrules",
    "COPILOT.md"
)

Write-Host "🔄 开始生成 agent guidance 入口文件..." -ForegroundColor Cyan

if (-Not (Test-Path -Path $SourceDoc)) {
    Write-Host "❌ 错误：源文档 '$SourceDoc' 不存在。" -ForegroundColor Red
    Write-Host "请先创建它，作为所有代理共享的中心真值。"
    exit 1
}

foreach ($file in $TargetFiles) {
    Write-Host "➡️ 正在生成 $file..."
    
    $content = @"
$GeneratedHeader

# Agent Workspace Instructions

This file is a thin entry point for coding agents working in this repository.

## Read First

1. \`$SourceDoc\` — shared cross-agent workflow principles.
2. Task-relevant files in \`my-skills/*.md\` before taking action.

## Drift Rule

- Do not copy large instruction blocks into this file.
- Update the central source document (\`$SourceDoc\`), then run \`.\scripts\multi-cli-sync\generate-guidance.ps1\`.
"@

    Set-Content -Path $file -Value $content -Encoding UTF8
    Write-Host "  ✔️ 已生成 $file" -ForegroundColor Green
}

Write-Host "✅ agent guidance 入口文件生成完成！" -ForegroundColor Cyan
