#!/usr/bin/env bun

/**
 * generate-guidance.ts - config-driven agent guidance entry generator.
 *
 * Usage:
 *   bun scripts/multi-cli-sync/generate-guidance.ts
 *   bun scripts/multi-cli-sync/generate-guidance.ts --check
 *   bun scripts/multi-cli-sync/generate-guidance.ts --config scripts/multi-cli-sync/guidance.config.json
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, isAbsolute, join } from "node:path";
import { fileURLToPath } from "node:url";

type SectionConfig = {
  ref?: string;
  heading?: string;
  body?: string;
  orderedItems?: string[];
  items?: string[];
};

type EntryConfig = {
  path: string;
  title: string;
  intro?: string;
  sections: SectionConfig[];
};

type GuidanceConfig = {
  generatedBy?: string;
  generatedHeader?: string;
  requiredSources?: string[];
  sharedSections?: Record<string, SectionConfig>;
  entries: EntryConfig[];
};

const scriptPath = fileURLToPath(import.meta.url);
const scriptDir = dirname(scriptPath);
const repoRoot = dirname(dirname(scriptDir));
const rawArgs = process.argv.slice(2);
const args = new Set(rawArgs);
const checkOnly = args.has("--check");

function normalize(text: string) {
  return text.replace(/\r\n/g, "\n").trimEnd();
}

function resolveConfigPath() {
  for (let index = 0; index < rawArgs.length; index += 1) {
    const arg = rawArgs[index];
    if (arg === "--config") {
      const value = rawArgs[index + 1];
      if (!value) {
        console.error("缺少 --config 参数值");
        process.exit(1);
      }
      return isAbsolute(value) ? value : join(repoRoot, value);
    }
    if (arg.startsWith("--config=")) {
      const value = arg.slice("--config=".length);
      return isAbsolute(value) ? value : join(repoRoot, value);
    }
  }
  return join(scriptDir, "guidance.config.json");
}

function repoPath(path: string) {
  return isAbsolute(path) ? path : join(repoRoot, path);
}

function loadConfig(path: string): GuidanceConfig {
  if (!existsSync(path)) {
    console.error(`缺少 guidance 配置文件：${path}`);
    process.exit(1);
  }

  try {
    return JSON.parse(readFileSync(path, "utf8")) as GuidanceConfig;
  } catch (error) {
    console.error(`无法解析 guidance 配置文件：${path}`);
    console.error(error);
    process.exit(1);
  }
}

function resolveSection(config: GuidanceConfig, section: SectionConfig): SectionConfig {
  if (!section.ref) {
    return section;
  }

  const shared = config.sharedSections?.[section.ref];
  if (!shared) {
    console.error(`guidance 配置引用了不存在的 shared section：${section.ref}`);
    process.exit(1);
  }

  return { ...shared, ...section, ref: undefined };
}

function renderSection(section: SectionConfig) {
  if (!section.heading) {
    console.error("guidance section 缺少 heading");
    process.exit(1);
  }

  const lines = [`## ${section.heading}`, ""];
  if (section.body) {
    lines.push(normalize(section.body), "");
  }
  if (section.orderedItems) {
    lines.push(...section.orderedItems.map((item, index) => `${index + 1}. ${item}`), "");
  }
  if (section.items) {
    lines.push(...section.items.map((item) => `- ${item}`), "");
  }
  return lines.join("\n");
}

function renderEntry(config: GuidanceConfig, entry: EntryConfig) {
  const header =
    config.generatedHeader ??
    `<!-- GENERATED BY ${config.generatedBy ?? "scripts/multi-cli-sync/generate-guidance.ts"}. DO NOT EDIT DIRECTLY. -->`;

  const lines = [header, `# ${entry.title}`, ""];
  if (entry.intro) {
    lines.push(normalize(entry.intro), "");
  }

  for (const rawSection of entry.sections) {
    lines.push(renderSection(resolveSection(config, rawSection)));
  }

  return normalize(lines.join("\n"));
}

const configPath = resolveConfigPath();
const config = loadConfig(configPath);

if (!Array.isArray(config.entries) || config.entries.length === 0) {
  console.error("guidance 配置必须包含 entries");
  process.exit(1);
}

const missingSources = (config.requiredSources ?? []).filter((path) => !existsSync(repoPath(path)));

if (missingSources.length > 0) {
  console.error(`缺少 guidance 源文件：\n${missingSources.map((item) => `- ${item}`).join("\n")}`);
  process.exit(1);
}

const drift: string[] = [];

for (const entry of config.entries) {
  const filePath = repoPath(entry.path);
  const expected = renderEntry(config, entry);
  const current = existsSync(filePath) ? normalize(readFileSync(filePath, "utf8")) : "";

  if (current !== expected) {
    drift.push(filePath);
    if (!checkOnly) {
      mkdirSync(dirname(filePath), { recursive: true });
      writeFileSync(filePath, `${expected}\n`, "utf8");
    }
  }
}

if (checkOnly) {
  if (drift.length > 0) {
    console.error(`检测到 agent guidance 漂移：\n${drift.map((item) => `- ${item}`).join("\n")}`);
    process.exit(1);
  }
  console.log("agent guidance 入口文件已同步");
} else if (drift.length > 0) {
  console.log(`已更新 agent guidance 入口文件：\n${drift.map((item) => `- ${item}`).join("\n")}`);
} else {
  console.log("agent guidance 入口文件本来就已同步");
}
