#!/usr/bin/env bash
# generate-guidance.sh - Zero-dependency script to generate thin AI guidance entry files

set -e

SOURCE_DOC="docs/agent-guidance/workflow.md"
GENERATED_HEADER="<!-- GENERATED BY scripts/generate-guidance.sh. DO NOT EDIT DIRECTLY. -->"

# -----------------------------------------------------------------------------
# Configuration: Define your target entry files here
# -----------------------------------------------------------------------------
# Example targets. The AI assistant can customize this array during /setup-sync
TARGET_FILES=(
    "AGENTS.md"
    "CLAUDE.md"
    ".cursorrules"
    "COPILOT.md"
)

echo "🔄 Generating agent guidance entry files..."

if [ ! -f "$SOURCE_DOC" ]; then
    echo "❌ Error: Source document '$SOURCE_DOC' does not exist."
    echo "Please create it so the agents have a central source of truth to read."
    exit 1
fi

for file in "${TARGET_FILES[@]}"; do
    echo "➡️ Generating $file..."
    
    # Generate the thin wrapper content
    cat > "$file" << EOF
$GENERATED_HEADER

# Agent Workspace Instructions

This file is a thin entry point for coding agents working in this repository.

## Read First

1. \`$SOURCE_DOC\` — shared cross-agent workflow principles.
2. Task-relevant files in \`my-skills/*.md\` before taking action.

## Drift Rule

- Do not copy large instruction blocks into this file.
- Update the central source document (\`$SOURCE_DOC\`), then run \`bash scripts/generate-guidance.sh\`.
EOF
    
    echo "  ✔️ Created $file"
done

echo "✅ Agent guidance generation complete!"
