# generate-guidance.ps1 - Zero-dependency PowerShell script to generate thin AI guidance entry files

$ErrorActionPreference = "Stop"

$SourceDoc = "docs/agent-guidance/workflow.md"
$GeneratedHeader = "<!-- GENERATED BY scripts/generate-guidance.ps1. DO NOT EDIT DIRECTLY. -->"

# -----------------------------------------------------------------------------
# Configuration: Define your target entry files here
# -----------------------------------------------------------------------------
$TargetFiles = @(
    "AGENTS.md",
    "CLAUDE.md",
    ".cursorrules",
    "COPILOT.md"
)

Write-Host "🔄 Generating agent guidance entry files..." -ForegroundColor Cyan

if (-Not (Test-Path -Path $SourceDoc)) {
    Write-Host "❌ Error: Source document '$SourceDoc' does not exist." -ForegroundColor Red
    Write-Host "Please create it so the agents have a central source of truth to read."
    exit 1
}

foreach ($file in $TargetFiles) {
    Write-Host "➡️ Generating $file..."
    
    $content = @"
$GeneratedHeader

# Agent Workspace Instructions

This file is a thin entry point for coding agents working in this repository.

## Read First

1. \`$SourceDoc\` — shared cross-agent workflow principles.
2. Task-relevant files in \`my-skills/*.md\` before taking action.

## Drift Rule

- Do not copy large instruction blocks into this file.
- Update the central source document (\`$SourceDoc\`), then run \`.\scripts\generate-guidance.ps1\`.
"@

    Set-Content -Path $file -Value $content -Encoding UTF8
    Write-Host "  ✔️ Created $file" -ForegroundColor Green
}

Write-Host "✅ Agent guidance generation complete!" -ForegroundColor Cyan
